import "./globals.css";
// import "react-toastify/dist/ReactToastify.css";

import { Inter } from "next/font/google";
// import { ToastContainer } from "react-toastify";

import Header from "@/components/header";
import { Providers } from "@/redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-slate-200`}
        suppressHydrationWarning={true}
      >
        <Header />
        <Providers>
          {children}
          {/* <ToastContainer /> */}
        </Providers>
      </body>
    </html>
  );
}
